export const translations = {
    ru: {
        title: "Описание",
        research: "<strong>EMM Research</strong> — независимое FX-исследование, сосредоточенное на динамике движения цены EUR/USD. Его цель — выявление возможностей генерации стабильной альфы на основе рыночных неэффективностей и разработка моделей, которые могут применяться как в <strong>дискреционном</strong> (ручном), так и в <strong>количественном</strong> (алготрейдинг) формате. Исследование проводится <strong>одним автором</strong>.",
        backtest: "В качестве иллюстрации прогресса исследования, <strong>EMM Backtest</strong> является частью результатов <strong>EMM Research</strong> и демонстрирует <strong>одну количественную модель</strong> – <strong>EMM Quinta Medulla Invariance</strong> с инвариантной логикой без переобучения на всём периоде. <strong>EMM Backtest</strong> полностью воспроизводим и методологически продуман благодаря пайплайну, криптографическим связкам, публичным исходным данным с классификацией по качеству, а также инженерному подходу. Тесты ориентированы исключительно на иллюстрацию одной модели за период с января 2001 по август 2025 года (24 года 8 месяцев) на минутных данных, начиная с момента введения наличных евро как единой валюты ЕС и приблизительной точки начала торговли на розничном рынке. В качестве дополнения проведён <strong> Cross-Asset Test на GBP/USD</strong>  без подгонки параметров, учитывая высокую корреляцию с EUR/USD до <strong>Brexit (2016)</strong>.",
        methodology: "Методология <strong>EMM Backtest</strong> была рассмотрена <a href=\"https://www.finbou.com\"><strong>Finbou AG</strong></a> (швейцарский CTA, специализирующийся на алгоритмических FX-стратегиях), в результате чего были предложены варианты проведения live due diligence.",
        focus: "Фокус на FX выбран из-за наличия регулирования валютных рынков на государственном уровне и системной реакции валютных пар на макроэкономические показатели, что делает рынок прозрачным и информативным для исследований. Конкретно EUR/USD выделена как самая ликвидная пара, являющаяся <strong>ядром FX</strong>, с наиболее стабильными структурными условиями для анализа и выявления особенностей ценовой динамики. Это подтверждается индексом доллара США (DXY) и сильной обратной зависимостью EUR/USD от него. Область исследования также охватывает другие основные валютные пары и некоторые кроссовые пары для выявления статистических закономерностей.",
        progress: "По предварительным оценкам, максимальный объём позиций, при котором сохраняется edge текущих моделей, ограничивает их применение малыми и средними CTA, family offices и розничными счетами. Этот предел эффективности отражает невозможность влияния на динамику цены и исчезновение реализуемой альфы на фоне высокой ликвидности и регулируемой среды рынка FX. Модели ориентированы на выявление и использование структурных особенностей FX-рынка, связанных с режимами волатильности, переоценкой ожиданий и нормализацией потоков после ключевых событий. Подход не предусматривает прогнозирования цены; он фокусируется на системных реакциях при определённых рыночных состояниях.",
    },
    en: {
        title: "About",
        research: "<strong>EMM Research</strong> is an independent FX study focused on the price dynamics of EUR/USD. Its goal is to identify opportunities for generating consistent alpha based on market inefficiencies and to develop models that can be applied either through <strong>discretionary</strong> (manual) trading or <strong>quantitative</strong> (algorithmic) approaches. The research is conducted by a <strong>single author</strong>.",
        backtest: "As an illustration of the research progress, <strong>EMM Backtest</strong> is part of the results of <strong>EMM Research</strong> and demonstrates a <strong>single quantitative model</strong> – <strong>EMM Quinta Medulla Invariance</strong> with invariant logic, without overfitting over the entire period. <strong>EMM Backtest</strong> is fully reproducible and methodologically robust, due to its pipeline, cryptographic bindings, publicly available input data classified by quality, and an engineering approach. The tests are designed solely to illustrate one model over the period from January 2001 to August 2025 (24 years 8 months) using minute-level data, starting from the introduction of cash euros as the single currency of the EU and approximately the beginning of retail trading. Additionally, a <strong>Cross Asset Test on GBP/USD</strong>  was conducted without parameter adjustments, considering the high correlation with EUR/USD prior to <strong>Brexit (2016)</strong>.",
        methodology: "The methodology of <strong>EMM Backtest</strong> was reviewed by <a href=\"https://www.finbou.com\"><strong>Finbou AG</strong></a> (a Swiss CTA specializing in algorithmic FX strategies), resulting in proposed approaches for live due diligence.",
        focus: "The focus on FX is driven by the presence of state-level regulation and the systematic response of currency pairs to macroeconomic indicators, making the market transparent and informative for research. EUR/USD is highlighted as the most liquid pair, forming the <strong>core of FX</strong>, with the most stable structural conditions for analyzing and identifying features of price dynamics. This is supported by the US Dollar Index (DXY) and the strong inverse relationship of EUR/USD to it. The research scope also covers other major currency pairs and certain cross pairs to identify statistical patterns.",
        progress: "According to preliminary estimates, the maximum position size at which the edge of the current models is preserved limits their applicability to small and medium-sized CTAs, family offices, and retail accounts. This efficiency limit reflects the impossibility of influencing price behavior and the persistence of exploitable alpha in the context of the FX market’s substantial liquidity and regulatory environment. The models leverage structural characteristics of the FX market, such as volatility regimes, expectation adjustments, and flow normalization following macroeconomic events. The approach is not based on forecasting but rather on conditional market responses under specific states."
    }
} as const;

export type Lang = keyof typeof translations; // "ru" | "en"